version: "3.9"

services:
  postgres:
    image: ${POSTGRES_IMAGE:-ankane/pgvector:pg16}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-azt3knet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-azt3knet}
      POSTGRES_DB: ${POSTGRES_DB:-azt3knet}
      POSTGRES_ENABLE_TIMESCALEDB: ${POSTGRES_ENABLE_TIMESCALEDB:-false}
      POSTGRES_SHARED_BUFFERS: ${POSTGRES_SHARED_BUFFERS:-256MB}
      TIMESCALEDB_MAX_MEMORY: ${TIMESCALEDB_MAX_MEMORY:-512MB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-azt3knet} -d ${POSTGRES_DB:-azt3knet}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres-data:
  ollama-data:
