version: "3.9"

services:
  postgres:
    image: ${POSTGRES_IMAGE:-ankane/pgvector:pg16}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-azt3knet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-azt3knet}
      POSTGRES_DB: ${POSTGRES_DB:-azt3knet}
      POSTGRES_ENABLE_TIMESCALEDB: ${POSTGRES_ENABLE_TIMESCALEDB:-false}
      POSTGRES_SHARED_BUFFERS: ${POSTGRES_SHARED_BUFFERS:-256MB}
      TIMESCALEDB_MAX_MEMORY: ${TIMESCALEDB_MAX_MEMORY:-512MB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-azt3knet} -d ${POSTGRES_DB:-azt3knet}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-azt3knet}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-azt3knet123}
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  prometheus:
    image: prom/prometheus:v2.53.1
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ../observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "${PROMETHEUS_SERVER_PORT:-9090}:9090"
    depends_on:
      redis:
        condition: service_started

  grafana:
    image: grafana/grafana:10.4.3
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-azt3knet}
    volumes:
      - grafana-data:/var/lib/grafana
      - ../observability/grafana:/etc/grafana/provisioning:ro
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    depends_on:
      prometheus:
        condition: service_started

volumes:
  postgres-data:
  ollama-data:
  minio-data:
  grafana-data:
